### ISSUE TITLE
http://vivoweb.org/ontology/core#sponsorAwardId

### ISSUE THREAD

**Issue by tawahle** [openrif/vivo-isf-ontology#754]
Just to clarify the purpose of this property: is it meant to be used for an ID **of the award** which is given by a particular sponsor organization? Or is it for an ID of the sponsor organization itself?

**Comment by mconlon17** [comment]
It is the id of the individual award.  A grant awarded by the NIH comes with a grant award number such as 1U2CDK119889-01.

**Comment by tawahle** [comment]
Thank you for the clarification!

**Comment by mconlon17** [comment]
Question answered
