### ISSUE TITLE
HR

### ISSUE THREAD

**Issue by Craite-team** [openrif/vivo-isf-ontology#757]
I need HR ontology for my research

**Comment by marijane** [comment]
I'm not sure VIVO-ISF is what you need; it describes the domain of scholarly academic research.

I did find a Human Resources Management Ontology at http://mayor2.dia.fi.upm.es/oeg-upm/index.php/en/ontologies/99-hrmontology/.  I have not reviewed it myself, however.  Good luck!

**Comment by Craite-team** [comment]
Thanks a lot. It helped a lot

**Comment by marijane** [comment]
You're welcome.
